global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'node'
    static_configs:
      - targets: ['127.0.0.1:9100']
    scrape_interval: 5s

  - job_name: 'process'
    static_configs:
      - targets: ['127.0.0.1:9256']
    scrape_interval: 5s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['127.0.0.1:15692']
    scrape_interval: 5s
    metrics_path: /metrics
    basic_auth:
      username: metrics
      password_file: /opt/zato/env/details/prom-password-rabbitmq

  - job_name: 'haproxy'
    static_configs:
      - targets: ['127.0.0.1:8404']
    scrape_interval: 5s
    metrics_path: /metrics
    basic_auth:
      username: metrics
      password_file: /opt/zato/env/details/prom-password-haproxy

  - job_name: 'pubsub-publish'
    static_configs:
      - targets: ['127.0.0.1:40100']
    scrape_interval: 5s
    metrics_path: /metrics
    basic_auth:
      username: metrics
      password_file: /opt/zato/env/details/prom-password-pubsub-publish

  - job_name: 'pubsub-pull'
    static_configs:
      - targets: ['127.0.0.1:40200']
    scrape_interval: 5s
    metrics_path: /metrics
    basic_auth:
      username: metrics
      password_file: /opt/zato/env/details/prom-password-pubsub-pull

  - job_name: 'zato-server'
    static_configs:
      - targets: ['127.0.0.1:17010']
    scrape_interval: 5s
    metrics_path: /metrics
    basic_auth:
      username: metrics
      password_file: /opt/zato/env/details/prom-password-server
